Added install script for frontend linters GH-110

diff --git a/_hooks/pre-commit b/_hooks/pre-commit
--- a/_hooks/pre-commit
+++ b/_hooks/pre-commit
@@ -33,14 +33,39 @@ run_linters() {
             fi
         fi
     done
-    
+
+    npm ls stylelint > /dev/null
+    exit_code=$?
+    if [[ $exit_code -ne 0 ]]; then
+        echo "stylelint not found!!"
+        read -p "Install linter?[y/n] " answer 
+        if [[ $answer =~ ^[Yy] ]]; then
+            npm install stylelint stylelint-config-standard -D
+        else
+            echo "Requirements not met, commit aborted."
+            exit 1
+        fi
+    fi
+
+    npm ls htmlhint > /dev/null
+    exit_code=$?
+    if [[ $exit_code -ne 0 ]]; then
+        echo "htmlhint not found!!"
+        read -p "Install linter?[y/n] " answer 
+        if [[ $answer =~ ^[Yy] ]]; then
+            npm install htmlhint -D
+        else
+            echo "Requirements not met, commit aborted."
+            exit 1
+        fi
+    fi
+
     # Reference for the following command https://git-scm.com/docs/git-diff 
     # Get the list of staged files
     staged_files=$(git diff --cached --name-only --diff-filter=AMR)
 
     # linters can be installed by command: pip install <linter_name>
-    echo "Running Python linters..."
-
+    echo "Running linters..."
     for file in $staged_files; do
         if [[ $file != */migrations/* && $file != *test* && $file != *settings* && $file != *init* && $file != *docs/* ]]; then
 
@@ -71,14 +96,14 @@ run_linters() {
                 
             elif [[ $file = *.html ]]; then
                 echo -e "HTMLHINT:" >> logs/linter.log
-                npx htmlhint . >> logs/linter.log
+                npx htmlhint $file >> logs/linter.log
 
             elif [[ $file = *.css ]]; then
                 echo -e "STYLELINT:" >> logs/linter.log
-                npx stylelint "**/*.css" >> logs/linter.log
+                npx stylelint $file >> logs/linter.log
             fi
             
-            echo -e "\n" >> logs/linter.log
+            echo -e "" >> logs/linter.log
             
             exit_code=$?
             if [ $exit_code -ne 0 ]; then
