Added setup script GH-9

diff --git a/_hooks/pre-commit b/_hooks/pre-commit
--- a/_hooks/pre-commit
+++ b/_hooks/pre-commit
@@ -1,17 +1,29 @@
 #!/bin/bash
 
-#########################################################################################
-#                                                                                       #
-#   In order use these commit hooks place them in the BASE_DIR/.git/hooks/<your-hook>   #
-#                                                                                       #  
-#########################################################################################
-
+# Needed in order to make read work in hook
+exec < /dev/tty
 run_python_linters() {
     # the logs will contain output from previous run only
     mkdir -p logs
     echo > logs/linter.log
     fail=false
-
+    
+    # Installing linters in case they are not installed
+    linters=(pylint flake8 ruff black pycodestyle pydocstyle)
+    for linter in ${linters[@]}; do 
+        pip show $linter > /dev/null
+        if [ $? -ne 0 ]; then
+            read -p "Install $linter?[y/n] " answer
+            if [[ $answer =~ ^[Yy] ]]; then
+                pip install $linter || exit 1
+            else
+                echo "Requirements not met, commit aborted."
+                exit 1
+            fi
+        fi
+    done
+    
+    # Reference for the following command https://git-scm.com/docs/git-diff 
     # Get the list of staged files
     staged_files=$(git diff --cached --name-only --diff-filter=AMR)
 
@@ -19,7 +31,7 @@ run_python_linters() {
     echo "Running Python linters..."
 
     for file in $staged_files; do
-        if [[ $file == *.py && $file != */migrations/* && $file != *test* && $file != *settings* && $file != *init* ]]; then
+        if [[ $file = *.py && $file != */migrations/* && $file != *test* && $file != *settings* && $file != *init* ]]; then
 
             echo -e "File Path: $file\n" >> logs/linter.log
 
@@ -53,12 +65,25 @@ run_python_linters() {
             type logs/linter.log
         fi 
     done
-    if   [ $fail ]; then
+    if [[ $fail != false ]]; then
         echo "Python linters failed, Commit aborted."
         echo "Please check terminal or logs in logs/linters.log"
         exit 1
     fi
 }
 
+ins_empty_line(){
+    # Get the list of staged files
+    staged_files=$(git diff --cached --name-only --diff-filter=AMR)
+
+    for file in $staged_files; do
+        last_line=$(tail -n 1 "$file")
+        if [ -n "$last_line" ]; then
+            echo "" >> "$file"
+        fi
+    done
+}
+
+ins_empty_line
 run_python_linters      
 
