Disabled commit messages which ends with "." GH-9

diff --git a/hooks/commit-msg b/hooks/commit-msg
--- a/hooks/commit-msg
+++ b/hooks/commit-msg
@@ -8,7 +8,7 @@
 
 commit_msg_file=$1
 
-# Get the first line of the commit message
+# Fetching the first line of the commit message
 commit_msg=$(head -n 1 "$commit_msg_file")
 
 max_length=50
@@ -16,6 +16,11 @@ max_length=50
 if [ ${#commit_msg} -gt $max_length ]; then
     echo "Error: Commit message length is greater than $max_length characters."
     echo "Please try to make it brief and descriptive."
+    exit 1
+fi
+
+if [[ "$commit_msg" == *"." ]]; then
+    echo "Error: Commit message should not end with a period."
     exit 1
 fi
 
